CREATE TABLE IF NOT EXISTS vaults (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    pin_hash TEXT NOT NULL,
    month_start_day INTEGER NOT NULL DEFAULT 1,
    vault_type TEXT NOT NULL DEFAULT 'Individual',
    is_admin INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    opening_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    is_primary INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    emoji TEXT NOT NULL,
    category_type TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    account_id BIGINT REFERENCES accounts(id),
    category_id BIGINT REFERENCES categories(id),
    date TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    transaction_type TEXT NOT NULL,
    notes TEXT,
    transfer_group_id TEXT,
    is_deleted INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS income_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    due_day INTEGER NOT NULL,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS commitments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    due_day INTEGER NOT NULL,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS obligation_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commitment_id BIGINT NOT NULL REFERENCES commitments(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    actual_amount DOUBLE PRECISION,
    status TEXT DEFAULT 'PENDING',
    notes TEXT,
    transaction_id BIGINT,
    UNIQUE(commitment_id, month, year)
);

CREATE TABLE IF NOT EXISTS income_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    income_template_id BIGINT NOT NULL REFERENCES income_templates(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    actual_amount DOUBLE PRECISION,
    status TEXT DEFAULT 'PENDING',
    notes TEXT,
    transaction_id BIGINT,
    UNIQUE(income_template_id, month, year)
);

CREATE TABLE IF NOT EXISTS monthly_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vault_id, month, year)
);

CREATE TABLE IF NOT EXISTS wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT '',
    estimated_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    saved_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    target_date TEXT,
    account_id BIGINT REFERENCES accounts(id),
    image_url TEXT,
    notes TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wishlist_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vault_id, name)
);

CREATE TABLE IF NOT EXISTS vault_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    shared_vault_id BIGINT NOT NULL REFERENCES vaults(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vault_id, shared_vault_id)
);

CREATE INDEX IF NOT EXISTS idx_accounts_vault_active
    ON accounts(vault_id, is_active);

CREATE INDEX IF NOT EXISTS idx_categories_vault_active
    ON categories(vault_id, is_active);

CREATE INDEX IF NOT EXISTS idx_transactions_vault_date
    ON transactions(vault_id, date);

CREATE INDEX IF NOT EXISTS idx_transactions_account
    ON transactions(account_id);

CREATE INDEX IF NOT EXISTS idx_transactions_category
    ON transactions(category_id);

CREATE INDEX IF NOT EXISTS idx_transactions_transfer_group
    ON transactions(transfer_group_id);

CREATE INDEX IF NOT EXISTS idx_commitments_vault_active
    ON commitments(vault_id, is_active);

CREATE INDEX IF NOT EXISTS idx_income_templates_vault_active
    ON income_templates(vault_id, is_active);

CREATE INDEX IF NOT EXISTS idx_wishlist_items_vault_active
    ON wishlist_items(vault_id, is_active);
