CREATE TABLE IF NOT EXISTS vaults (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    pin_hash TEXT NOT NULL,
    month_start_day INTEGER NOT NULL DEFAULT 1,
    financial_cycle_start_day INTEGER NOT NULL DEFAULT 1,
    monthly_savings_goal DOUBLE PRECISION NOT NULL DEFAULT 0,
    vault_type TEXT NOT NULL DEFAULT 'Individual',
    is_admin INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    opening_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    is_primary INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT REFERENCES vaults(id),
    name TEXT NOT NULL,
    emoji TEXT NOT NULL,
    parent_category TEXT,
    category_type TEXT NOT NULL,
    is_system INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    beneficiary_vault_id BIGINT REFERENCES vaults(id),
    account_id BIGINT REFERENCES accounts(id),
    category_id BIGINT REFERENCES categories(id),
    date TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    transaction_type TEXT NOT NULL,
    allocation_method TEXT,
    notes TEXT,
    transfer_group_id TEXT,
    is_deleted INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS income_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    due_day INTEGER NOT NULL,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS commitments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    due_day INTEGER NOT NULL,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS obligation_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commitment_id BIGINT NOT NULL REFERENCES commitments(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    actual_amount DOUBLE PRECISION,
    status TEXT DEFAULT 'PENDING',
    notes TEXT,
    transaction_id BIGINT,
    UNIQUE(commitment_id, month, year)
);

CREATE TABLE IF NOT EXISTS income_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    income_template_id BIGINT NOT NULL REFERENCES income_templates(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    actual_amount DOUBLE PRECISION,
    status TEXT DEFAULT 'PENDING',
    notes TEXT,
    transaction_id BIGINT,
    UNIQUE(income_template_id, month, year)
);

CREATE TABLE IF NOT EXISTS monthly_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vault_id, month, year)
);

CREATE TABLE IF NOT EXISTS financial_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    UNIQUE(vault_id, start_date)
);

CREATE TABLE IF NOT EXISTS cycle_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES financial_cycles(id) ON DELETE CASCADE,
    participant_vault_id BIGINT NOT NULL REFERENCES vaults(id),
    income DOUBLE PRECISION NOT NULL DEFAULT 0,
    income_ratio DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(cycle_id, participant_vault_id)
);

CREATE TABLE IF NOT EXISTS wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT '',
    estimated_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    saved_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    target_date TEXT,
    account_id BIGINT REFERENCES accounts(id),
    image_url TEXT,
    notes TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wishlist_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vault_id, name)
);

CREATE TABLE IF NOT EXISTS vault_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_id BIGINT NOT NULL REFERENCES vaults(id),
    shared_vault_id BIGINT NOT NULL REFERENCES vaults(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vault_id, shared_vault_id)
);

CREATE TABLE IF NOT EXISTS transaction_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    participant_vault_id BIGINT NOT NULL REFERENCES vaults(id),
    share_amount DOUBLE PRECISION NOT NULL,
    share_percentage DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(transaction_id, participant_vault_id)
);

CREATE TABLE IF NOT EXISTS shared_bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_vault_id BIGINT NOT NULL REFERENCES vaults(id),
    name TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    due_day INTEGER NOT NULL,
    category_id BIGINT REFERENCES categories(id),
    frequency TEXT NOT NULL DEFAULT 'Monthly',
    start_date TEXT,
    end_date TEXT,
    notes TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shared_bill_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shared_vault_id BIGINT NOT NULL REFERENCES vaults(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'Active',
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    paid_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    remaining_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(shared_vault_id, month, year)
);

CREATE TABLE IF NOT EXISTS shared_bill_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES shared_bill_cycles(id) ON DELETE CASCADE,
    bill_id BIGINT NOT NULL REFERENCES shared_bills(id),
    name TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    due_date TEXT NOT NULL,
    frequency TEXT NOT NULL,
    category_id BIGINT REFERENCES categories(id),
    status TEXT NOT NULL DEFAULT 'Pending',
    payer_vault_id BIGINT REFERENCES vaults(id),
    payment_date TEXT,
    payment_notes TEXT,
    transaction_id BIGINT REFERENCES transactions(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(cycle_id, bill_id)
);

CREATE TABLE IF NOT EXISTS shared_bill_instance_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_instance_id BIGINT NOT NULL REFERENCES shared_bill_instances(id) ON DELETE CASCADE,
    participant_vault_id BIGINT NOT NULL REFERENCES vaults(id),
    expected_amount DOUBLE PRECISION NOT NULL,
    expected_percentage DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(bill_instance_id, participant_vault_id)
);

ALTER TABLE shared_bills
    ADD COLUMN IF NOT EXISTS frequency TEXT NOT NULL DEFAULT 'Monthly';

ALTER TABLE shared_bills
    ADD COLUMN IF NOT EXISTS start_date TEXT;

ALTER TABLE shared_bills
    ADD COLUMN IF NOT EXISTS end_date TEXT;

UPDATE shared_bills
SET start_date = COALESCE(start_date, TO_CHAR(created_at, 'YYYY-MM-01'))
WHERE start_date IS NULL;

ALTER TABLE vaults
    ADD COLUMN IF NOT EXISTS financial_cycle_start_day INTEGER NOT NULL DEFAULT 1;

ALTER TABLE financial_cycles
    DROP COLUMN IF EXISTS status;

DROP TABLE IF EXISTS notifications;

ALTER TABLE vaults
    ADD COLUMN IF NOT EXISTS monthly_savings_goal DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE categories
    ALTER COLUMN vault_id DROP NOT NULL;

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS parent_category TEXT;

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS is_system INTEGER NOT NULL DEFAULT 0;

INSERT INTO categories (vault_id, name, emoji, parent_category, category_type, is_system, is_active)
SELECT
    seed.vault_id::BIGINT,
    seed.name::TEXT,
    seed.emoji::TEXT,
    seed.parent_category::TEXT,
    seed.category_type::TEXT,
    seed.is_system::INTEGER,
    seed.is_active::INTEGER
FROM (
VALUES
    (NULL, 'Rent', 'home', 'Household', 'Expense', 1, 1),
    (NULL, 'Groceries', 'shopping_cart', 'Household', 'Expense', 1, 1),
    (NULL, 'Utilities', 'bolt', 'Household', 'Expense', 1, 1),
    (NULL, 'Internet', 'wifi', 'Household', 'Expense', 1, 1),
    (NULL, 'Household Supplies', 'inventory_2', 'Household', 'Expense', 1, 1),
    (NULL, 'Furniture & Appliances', 'chair', 'Household', 'Expense', 1, 1),
    (NULL, 'Maintenance', 'home_repair_service', 'Household', 'Expense', 1, 1),
    (NULL, 'Dining Out', 'restaurant', 'Food & Drinks', 'Expense', 1, 1),
    (NULL, 'Coffee & Cafés', 'local_cafe', 'Food & Drinks', 'Expense', 1, 1),
    (NULL, 'Food Delivery', 'delivery_dining', 'Food & Drinks', 'Expense', 1, 1),
    (NULL, 'Snacks', 'bakery_dining', 'Food & Drinks', 'Expense', 1, 1),
    (NULL, 'Fuel', 'local_gas_station', 'Transport', 'Expense', 1, 1),
    (NULL, 'Public Transport', 'directions_bus', 'Transport', 'Expense', 1, 1),
    (NULL, 'Cab / Auto', 'local_taxi', 'Transport', 'Expense', 1, 1),
    (NULL, 'Parking', 'local_parking', 'Transport', 'Expense', 1, 1),
    (NULL, 'Vehicle Maintenance', 'car_repair', 'Transport', 'Expense', 1, 1),
    (NULL, 'Pharmacy', 'local_pharmacy', 'Health', 'Expense', 1, 1),
    (NULL, 'Doctor', 'medical_services', 'Health', 'Expense', 1, 1),
    (NULL, 'Fitness', 'fitness_center', 'Health', 'Expense', 1, 1),
    (NULL, 'Insurance', 'health_and_safety', 'Health', 'Expense', 1, 1),
    (NULL, 'Clothing', 'checkroom', 'Shopping', 'Expense', 1, 1),
    (NULL, 'Electronics', 'devices', 'Shopping', 'Expense', 1, 1),
    (NULL, 'Personal Care', 'spa', 'Shopping', 'Expense', 1, 1),
    (NULL, 'Home Shopping', 'shopping_bag', 'Shopping', 'Expense', 1, 1),
    (NULL, 'Gifts', 'redeem', 'Shopping', 'Expense', 1, 1),
    (NULL, 'Entertainment', 'movie', 'Lifestyle', 'Expense', 1, 1),
    (NULL, 'Subscriptions', 'subscriptions', 'Lifestyle', 'Expense', 1, 1),
    (NULL, 'Hobbies', 'palette', 'Lifestyle', 'Expense', 1, 1),
    (NULL, 'Travel', 'flight', 'Lifestyle', 'Expense', 1, 1),
    (NULL, 'Events', 'event', 'Lifestyle', 'Expense', 1, 1),
    (NULL, 'Investment', 'trending_up', 'Financial', 'Expense', 1, 1),
    (NULL, 'Savings', 'savings', 'Financial', 'Expense', 1, 1),
    (NULL, 'EMI', 'payments', 'Financial', 'Expense', 1, 1),
    (NULL, 'Taxes', 'receipt_long', 'Financial', 'Expense', 1, 1),
    (NULL, 'Bank Charges', 'account_balance', 'Financial', 'Expense', 1, 1),
    (NULL, 'Courses', 'school', 'Education', 'Expense', 1, 1),
    (NULL, 'Books', 'menu_book', 'Education', 'Expense', 1, 1),
    (NULL, 'Certifications', 'workspace_premium', 'Education', 'Expense', 1, 1),
    (NULL, 'Miscellaneous', 'category', 'Miscellaneous', 'Expense', 1, 1)
) AS seed(vault_id, name, emoji, parent_category, category_type, is_system, is_active)
WHERE NOT EXISTS (
    SELECT 1
    FROM categories existing
    WHERE existing.is_system = 1
    AND LOWER(existing.name) = LOWER(seed.name)
);

WITH desired_system_categories(name, emoji, parent_category) AS (
VALUES
    ('Default', '🏷️', 'Miscellaneous'),
    ('Groceries', '🛒', 'Household'),
    ('Home', '🏡', 'Household'),
    ('Dining Out', '🍽', 'Food & Drinks'),
    ('Coffee', '☕', 'Food & Drinks'),
    ('Food Delivery', '🛵', 'Food & Drinks'),
    ('Fuel', '⛽', 'Transport'),
    ('Transport', '🚕', 'Transport'),
    ('Medical', '🏥', 'Health'),
    ('Fitness', '💪', 'Health'),
    ('Shopping', '🛍', 'Shopping'),
    ('Entertainment', '🎬', 'Lifestyle'),
    ('Subscriptions', '📺', 'Lifestyle'),
    ('Travel', '✈️', 'Lifestyle'),
    ('Miscellaneous', '📦', 'Miscellaneous')
)
UPDATE categories c
SET
    vault_id = NULL,
    emoji = desired.emoji,
    parent_category = desired.parent_category,
    category_type = 'Expense',
    is_system = 1,
    is_active = 1
FROM desired_system_categories desired
WHERE c.is_system = 1
AND LOWER(c.name) = LOWER(desired.name);

WITH desired_system_categories(name, emoji, parent_category) AS (
VALUES
    ('Default', '🏷️', 'Miscellaneous'),
    ('Groceries', '🛒', 'Household'),
    ('Home', '🏡', 'Household'),
    ('Dining Out', '🍽', 'Food & Drinks'),
    ('Coffee', '☕', 'Food & Drinks'),
    ('Food Delivery', '🛵', 'Food & Drinks'),
    ('Fuel', '⛽', 'Transport'),
    ('Transport', '🚕', 'Transport'),
    ('Medical', '🏥', 'Health'),
    ('Fitness', '💪', 'Health'),
    ('Shopping', '🛍', 'Shopping'),
    ('Entertainment', '🎬', 'Lifestyle'),
    ('Subscriptions', '📺', 'Lifestyle'),
    ('Travel', '✈️', 'Lifestyle'),
    ('Miscellaneous', '📦', 'Miscellaneous')
)
INSERT INTO categories (vault_id, name, emoji, parent_category, category_type, is_system, is_active)
SELECT
    NULL::BIGINT,
    desired.name::TEXT,
    desired.emoji::TEXT,
    desired.parent_category::TEXT,
    'Expense',
    1,
    1
FROM desired_system_categories desired
WHERE NOT EXISTS (
    SELECT 1
    FROM categories existing
    WHERE existing.is_system = 1
    AND LOWER(existing.name) = LOWER(desired.name)
);

WITH desired_system_categories(name) AS (
VALUES
    ('Default'),
    ('Groceries'),
    ('Home'),
    ('Dining Out'),
    ('Coffee'),
    ('Food Delivery'),
    ('Fuel'),
    ('Transport'),
    ('Medical'),
    ('Fitness'),
    ('Shopping'),
    ('Entertainment'),
    ('Subscriptions'),
    ('Travel'),
    ('Miscellaneous')
)
UPDATE categories c
SET is_active = 0
WHERE c.is_system = 1
AND NOT EXISTS (
    SELECT 1
    FROM desired_system_categories desired
    WHERE LOWER(desired.name) = LOWER(c.name)
);

UPDATE transactions t
SET category_id = sc.id
FROM categories old
JOIN categories sc
    ON sc.is_system = 1
    AND LOWER(sc.name) = LOWER(old.name)
WHERE t.category_id = old.id
AND old.is_system = 0;

UPDATE categories old
SET is_active = 0
WHERE old.is_system = 0
AND EXISTS (
    SELECT 1
    FROM categories sc
    WHERE sc.is_system = 1
    AND LOWER(sc.name) = LOWER(old.name)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_system_name
    ON categories(LOWER(name))
    WHERE is_system = 1;

UPDATE vaults
SET financial_cycle_start_day = COALESCE(financial_cycle_start_day, month_start_day, 1);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_financial_cycle_start_day'
    ) THEN
        ALTER TABLE vaults
            ADD CONSTRAINT chk_financial_cycle_start_day
            CHECK (financial_cycle_start_day BETWEEN 1 AND 28);
    END IF;
END $$;

INSERT INTO financial_cycles (
    vault_id,
    start_date,
    end_date,
    created_at
)
SELECT
    v.id,
    (
        MAKE_DATE(mc.year, mc.month, LEAST(COALESCE(v.financial_cycle_start_day, v.month_start_day, 1), 28))
    )::text AS start_date,
    (
        MAKE_DATE(mc.year, mc.month, LEAST(COALESCE(v.financial_cycle_start_day, v.month_start_day, 1), 28))
        + INTERVAL '1 month'
        - INTERVAL '1 day'
    )::date::text AS end_date,
    mc.created_at
FROM monthly_cycles mc
JOIN vaults v
    ON v.id = mc.vault_id
ON CONFLICT (vault_id, start_date) DO NOTHING;

ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS beneficiary_vault_id BIGINT REFERENCES vaults(id);

ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS allocation_method TEXT;

UPDATE transactions
SET beneficiary_vault_id = vault_id
WHERE beneficiary_vault_id IS NULL;

ALTER TABLE transactions
    ALTER COLUMN beneficiary_vault_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_accounts_vault_active
    ON accounts(vault_id, is_active);

CREATE INDEX IF NOT EXISTS idx_categories_vault_active
    ON categories(vault_id, is_active);

CREATE INDEX IF NOT EXISTS idx_transactions_vault_date
    ON transactions(vault_id, date);

DROP INDEX IF EXISTS idx_financial_cycles_one_active;

CREATE INDEX IF NOT EXISTS idx_financial_cycles_vault_dates
    ON financial_cycles(vault_id, start_date, end_date);

CREATE INDEX IF NOT EXISTS idx_cycle_contributions_cycle
    ON cycle_contributions(cycle_id);

CREATE INDEX IF NOT EXISTS idx_transactions_beneficiary
    ON transactions(beneficiary_vault_id);

CREATE INDEX IF NOT EXISTS idx_transactions_account
    ON transactions(account_id);

CREATE INDEX IF NOT EXISTS idx_transactions_category
    ON transactions(category_id);

CREATE INDEX IF NOT EXISTS idx_transactions_transfer_group
    ON transactions(transfer_group_id);

CREATE INDEX IF NOT EXISTS idx_transaction_shares_transaction
    ON transaction_shares(transaction_id);

CREATE INDEX IF NOT EXISTS idx_transaction_shares_participant
    ON transaction_shares(participant_vault_id);

CREATE INDEX IF NOT EXISTS idx_shared_bills_vault_active
    ON shared_bills(shared_vault_id, is_active);

CREATE INDEX IF NOT EXISTS idx_shared_bill_cycles_vault_period
    ON shared_bill_cycles(shared_vault_id, year, month);

CREATE INDEX IF NOT EXISTS idx_shared_bill_instances_cycle_status
    ON shared_bill_instances(cycle_id, status);

CREATE INDEX IF NOT EXISTS idx_shared_bill_instance_shares_instance
    ON shared_bill_instance_shares(bill_instance_id);

CREATE INDEX IF NOT EXISTS idx_commitments_vault_active
    ON commitments(vault_id, is_active);

CREATE INDEX IF NOT EXISTS idx_income_templates_vault_active
    ON income_templates(vault_id, is_active);

CREATE INDEX IF NOT EXISTS idx_wishlist_items_vault_active
    ON wishlist_items(vault_id, is_active);
