from __future__ import annotations

import json
from dataclasses import dataclass
from enum import Enum
from typing import Any, Optional

from db.core import get_connection


class DraftStatus(str, Enum):
    NEEDS_REVIEW = "NEEDS_REVIEW"
    READY_TO_APPROVE = "READY_TO_APPROVE"
    FAILED = "FAILED"
    DELETED = "DELETED"
    APPROVED = "APPROVED"


@dataclass
class DraftTransactionRecord:
    id: Optional[int]
    vault_id: int
    raw_text: str
    transaction_type: Optional[str]
    merchant: Optional[str]
    amount: Optional[float]
    currency: str
    account_name: Optional[str]
    account_id: Optional[int]
    category_name: Optional[str]
    category_id: Optional[int]
    date: Optional[str]
    notes: Optional[str]
    confidence: dict[str, Any]
    status: str
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    approved_at: Optional[str] = None
    duplicate: bool = False
    existing_transaction_id: Optional[int] = None


def ensure_capture_schema_with_cursor(cursor) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS draft_transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            vault_id BIGINT NOT NULL REFERENCES vaults(id),
            raw_text TEXT NOT NULL,
            transaction_type TEXT,
            merchant TEXT,
            amount DOUBLE PRECISION,
            currency TEXT NOT NULL DEFAULT 'INR',
            account_name TEXT,
            account_id BIGINT REFERENCES accounts(id),
            category_name TEXT,
            category_id BIGINT REFERENCES categories(id),
            date TEXT,
            notes TEXT,
            confidence TEXT NOT NULL DEFAULT '{}',
            status TEXT NOT NULL DEFAULT 'NEEDS_REVIEW',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            approved_at TIMESTAMPTZ
        )
        """,
        capture_lastrowid=False,
    )
    cursor.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_draft_transactions_vault_status_created
            ON draft_transactions(vault_id, status, created_at DESC)
        """,
        capture_lastrowid=False,
    )


def ensure_capture_schema() -> None:
    conn = get_connection()
    try:
        ensure_capture_schema_with_cursor(conn.cursor())
        conn.commit()
    finally:
        conn.close()


def _confidence_to_json(confidence: dict[str, Any] | None) -> str:
    return json.dumps(confidence or {})


def _confidence_from_json(value: Any) -> dict[str, Any]:
    if value is None:
        return {}
    if isinstance(value, dict):
        return value
    try:
        loaded = json.loads(value)
        return loaded if isinstance(loaded, dict) else {}
    except (TypeError, ValueError, json.JSONDecodeError):
        return {}


def _row_to_record(row) -> DraftTransactionRecord:
    return DraftTransactionRecord(
        id=int(row[0]),
        vault_id=int(row[1]),
        raw_text=row[2] or "",
        transaction_type=row[3],
        merchant=row[4],
        amount=float(row[5]) if row[5] is not None else None,
        currency=row[6] or "INR",
        account_name=row[7],
        account_id=int(row[8]) if row[8] is not None else None,
        category_name=row[9],
        category_id=int(row[10]) if row[10] is not None else None,
        date=str(row[11]) if row[11] is not None else None,
        notes=row[12],
        confidence=_confidence_from_json(row[13]),
        status=row[14],
        created_at=str(row[15]) if row[15] is not None else None,
        updated_at=str(row[16]) if row[16] is not None else None,
        approved_at=str(row[17]) if row[17] is not None else None,
    )


_SELECT_COLUMNS = """
    id,
    vault_id,
    raw_text,
    transaction_type,
    merchant,
    amount,
    currency,
    account_name,
    account_id,
    category_name,
    category_id,
    date,
    notes,
    confidence,
    status,
    created_at,
    updated_at,
    approved_at
"""


def insert_draft(
    vault_id: int,
    raw_text: str,
    transaction_type: Optional[str],
    merchant: Optional[str],
    amount: Optional[float],
    currency: str,
    account_name: Optional[str],
    account_id: Optional[int],
    category_name: Optional[str],
    category_id: Optional[int],
    txn_date: Optional[str],
    notes: Optional[str],
    confidence: dict[str, Any],
    status: str,
) -> DraftTransactionRecord:
    ensure_capture_schema()
    conn = get_connection()
    try:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT INTO draft_transactions (
                vault_id,
                raw_text,
                transaction_type,
                merchant,
                amount,
                currency,
                account_name,
                account_id,
                category_name,
                category_id,
                date,
                notes,
                confidence,
                status
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                vault_id,
                raw_text,
                transaction_type,
                merchant,
                amount,
                currency or "INR",
                account_name,
                account_id,
                category_name,
                category_id,
                txn_date,
                notes,
                _confidence_to_json(confidence),
                status,
            ),
        )
        draft_id = cursor.lastrowid
        conn.commit()
        record = get_draft_by_id(int(draft_id), vault_id)
        if record is None:
            raise RuntimeError("Draft transaction was not created.")
        return record
    finally:
        conn.close()


def get_draft_by_id(draft_id: int, vault_id: int) -> Optional[DraftTransactionRecord]:
    ensure_capture_schema()
    conn = get_connection()
    try:
        row = conn.execute(
            f"""
            SELECT {_SELECT_COLUMNS}
            FROM draft_transactions
            WHERE id = ?
            AND vault_id = ?
            """,
            (draft_id, vault_id),
        ).fetchone()
        if not row:
            return None
        return _row_to_record(row)
    finally:
        conn.close()


def list_inbox_drafts(vault_id: int) -> list[DraftTransactionRecord]:
    ensure_capture_schema()
    conn = get_connection()
    try:
        rows = conn.execute(
            f"""
            SELECT {_SELECT_COLUMNS}
            FROM draft_transactions
            WHERE vault_id = ?
            AND status IN (?, ?, ?)
            ORDER BY created_at DESC, id DESC
            """,
            (
                vault_id,
                DraftStatus.NEEDS_REVIEW.value,
                DraftStatus.READY_TO_APPROVE.value,
                DraftStatus.FAILED.value,
            ),
        ).fetchall()
        return [_row_to_record(row) for row in rows]
    finally:
        conn.close()


def soft_delete_draft(draft_id: int, vault_id: int) -> Optional[DraftTransactionRecord]:
    ensure_capture_schema()
    existing = get_draft_by_id(draft_id, vault_id)
    if existing is None:
        return None
    if existing.status in (DraftStatus.DELETED.value, DraftStatus.APPROVED.value):
        return None

    conn = get_connection()
    try:
        cursor = conn.cursor()
        cursor.execute(
            """
            UPDATE draft_transactions
            SET
                status = ?,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
            AND vault_id = ?
            """,
            (
                DraftStatus.DELETED.value,
                draft_id,
                vault_id,
            ),
            capture_lastrowid=False,
        )
        conn.commit()
    finally:
        conn.close()

    return get_draft_by_id(draft_id, vault_id)


def mark_draft_approved(draft_id: int, vault_id: int) -> Optional[DraftTransactionRecord]:
    ensure_capture_schema()
    existing = get_draft_by_id(draft_id, vault_id)
    if existing is None:
        return None
    if existing.status not in (
        DraftStatus.NEEDS_REVIEW.value,
        DraftStatus.READY_TO_APPROVE.value,
    ):
        return None

    conn = get_connection()
    try:
        cursor = conn.cursor()
        cursor.execute(
            """
            UPDATE draft_transactions
            SET
                status = ?,
                approved_at = CURRENT_TIMESTAMP,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
            AND vault_id = ?
            """,
            (
                DraftStatus.APPROVED.value,
                draft_id,
                vault_id,
            ),
            capture_lastrowid=False,
        )
        conn.commit()
    finally:
        conn.close()

    return get_draft_by_id(draft_id, vault_id)


def resolve_account_for_vault(
    vault_id: int,
    account_name: Optional[str],
    account_hint: Optional[str],
) -> tuple[Optional[int], Optional[str], int]:
    """Match vault accounts by last digits or fuzzy name. Returns (id, name, confidence)."""
    conn = get_connection()
    try:
        rows = conn.execute(
            """
            SELECT id, name, type
            FROM accounts
            WHERE vault_id = ?
            AND is_active = 1
            ORDER BY is_primary DESC, id
            """,
            (vault_id,),
        ).fetchall()
    finally:
        conn.close()

    if not rows:
        return None, account_name, 0

    hint = (account_hint or "").strip().lower()
    name_hint = (account_name or "").strip().lower()

    if hint.isdigit():
        for row in rows:
            account_label = str(row[1] or "")
            digits = "".join(ch for ch in account_label if ch.isdigit())
            if digits.endswith(hint):
                return int(row[0]), str(row[1]), 88

    search = hint or name_hint
    if search:
        for row in rows:
            label = f"{row[1]} {row[2]}".lower()
            if search in label or any(token and token in label for token in search.split()):
                return int(row[0]), str(row[1]), 70

    # Prefer primary account as soft suggestion only when we have an account hint.
    if account_name or account_hint:
        primary = rows[0]
        return int(primary[0]), str(primary[1]), 35

    return None, account_name, 0


def resolve_category_for_vault(
    vault_id: int,
    category_name: Optional[str],
    transaction_type: Optional[str],
) -> tuple[Optional[int], Optional[str], int]:
    if not category_name:
        return None, None, 0

    conn = get_connection()
    try:
        row = conn.execute(
            """
            SELECT id, name
            FROM categories
            WHERE is_active = 1
            AND LOWER(name) = LOWER(?)
            AND (
                vault_id = ?
                OR is_system = 1
            )
            ORDER BY is_system ASC, id
            LIMIT 1
            """,
            (category_name, vault_id),
        ).fetchone()

        if row:
            return int(row[0]), str(row[1]), 90

        # Soft match: category name contained in vault categories.
        rows = conn.execute(
            """
            SELECT id, name
            FROM categories
            WHERE is_active = 1
            AND (
                vault_id = ?
                OR is_system = 1
            )
            ORDER BY is_system ASC, id
            """,
            (vault_id,),
        ).fetchall()
    finally:
        conn.close()

    target = category_name.strip().lower()
    for row in rows:
        name = str(row[1] or "")
        if target in name.lower() or name.lower() in target:
            return int(row[0]), name, 65

    return None, category_name, 25


def default_category_id(vault_id: int) -> Optional[int]:
    from db.core import ensure_default_category

    try:
        return int(ensure_default_category(vault_id))
    except Exception:
        return None
