"""Dedicated settlement audit trail for shared vaults.

Settlements are first-class entities. Transfer rows created for account
balances are a side effect of recording a settlement, not the source of
settlement history.
"""

from __future__ import annotations

from db.core import TRANSFER_IN, TRANSFER_OUT, get_connection
from db.financial_cycles import get_current_cycle
from db.shared_expenses import (
    as_money,
    build_settlements_from_balances,
    get_shared_balances_with_cursor,
)

SETTLEMENT_STATUS_FULL = "FULL"
SETTLEMENT_STATUS_PARTIAL = "PARTIAL"
SETTLEMENT_STATUS_ADJUSTMENT = "ADJUSTMENT"

SETTLEMENT_FILTER_ALL = "all"
SETTLEMENT_FILTER_RECEIVED = "received"
SETTLEMENT_FILTER_SENT = "sent"

_EPSILON = 0.005


def ensure_settlements_schema_with_cursor(cursor) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS settlements (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            shared_vault_id BIGINT NOT NULL REFERENCES vaults(id),
            from_participant_id BIGINT NOT NULL REFERENCES vaults(id),
            to_participant_id BIGINT NOT NULL REFERENCES vaults(id),
            amount DOUBLE PRECISION NOT NULL,
            status TEXT NOT NULL,
            payment_method TEXT,
            notes TEXT,
            outstanding_before DOUBLE PRECISION,
            outstanding_after DOUBLE PRECISION,
            transfer_group_id TEXT,
            settled_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        capture_lastrowid=False,
    )
    cursor.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_settlements_shared_settled
            ON settlements(shared_vault_id, settled_at DESC, id DESC)
        """,
        capture_lastrowid=False,
    )
    cursor.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_settlements_transfer_group
            ON settlements(transfer_group_id)
            WHERE transfer_group_id IS NOT NULL
        """,
        capture_lastrowid=False,
    )


def ensure_settlements_schema() -> None:
    conn = get_connection()
    try:
        ensure_settlements_schema_with_cursor(conn.cursor())
        conn.commit()
    finally:
        conn.close()


def participant_initials(name: str | None) -> str:
    parts = [part for part in (name or "").strip().split() if part]
    if not parts:
        return "?"
    if len(parts) == 1:
        return parts[0][:2].upper()
    return f"{parts[0][0]}{parts[-1][0]}".upper()


def settlement_status_for_amounts(outstanding_before: float, amount: float) -> str:
    remaining = as_money(max(0.0, outstanding_before - amount))
    if remaining <= _EPSILON:
        return SETTLEMENT_STATUS_FULL
    return SETTLEMENT_STATUS_PARTIAL


def outstanding_between_participants(
    cursor,
    shared_vault_id: int,
    from_participant_id: int,
    to_participant_id: int,
    start_date: str,
    end_date: str,
) -> float | None:
    balances = get_shared_balances_with_cursor(
        cursor,
        shared_vault_id,
        start_date,
        end_date,
    )
    for item in build_settlements_from_balances(balances):
        if (
            item["from_vault_id"] == from_participant_id
            and item["to_vault_id"] == to_participant_id
        ):
            return as_money(item["amount"])
    return None


def insert_settlement_with_cursor(
    cursor,
    *,
    shared_vault_id: int,
    from_participant_id: int,
    to_participant_id: int,
    amount: float,
    status: str,
    payment_method: str | None,
    notes: str | None,
    outstanding_before: float | None,
    outstanding_after: float | None,
    transfer_group_id: str | None,
    settled_at: str,
):
    cursor.execute(
        """
        INSERT INTO settlements (
            shared_vault_id,
            from_participant_id,
            to_participant_id,
            amount,
            status,
            payment_method,
            notes,
            outstanding_before,
            outstanding_after,
            transfer_group_id,
            settled_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            shared_vault_id,
            from_participant_id,
            to_participant_id,
            as_money(amount),
            status,
            payment_method,
            notes,
            None if outstanding_before is None else as_money(outstanding_before),
            None if outstanding_after is None else as_money(outstanding_after),
            transfer_group_id,
            settled_at,
        ),
    )
    return int(cursor.lastrowid) if cursor.lastrowid else None


def create_settlement_record(
    cursor,
    *,
    shared_vault_id: int,
    from_participant_id: int,
    to_participant_id: int,
    amount: float,
    settlement_date: str,
    transfer_group_id: str | None = None,
    payment_method: str | None = None,
    notes: str | None = None,
    status: str | None = None,
):
    cycle = get_current_cycle(shared_vault_id)
    outstanding_before = outstanding_between_participants(
        cursor,
        shared_vault_id,
        from_participant_id,
        to_participant_id,
        cycle.start_iso,
        cycle.end_iso,
    )
    if outstanding_before is None:
        outstanding_before = as_money(amount)

    amount_value = as_money(amount)
    outstanding_after = as_money(max(0.0, outstanding_before - amount_value))
    resolved_status = status or settlement_status_for_amounts(
        outstanding_before,
        amount_value,
    )

    settled_at = settlement_date
    if len(settled_at) == 10:
        settled_at = f"{settled_at}T12:00:00+00:00"

    settlement_id = insert_settlement_with_cursor(
        cursor,
        shared_vault_id=shared_vault_id,
        from_participant_id=from_participant_id,
        to_participant_id=to_participant_id,
        amount=amount_value,
        status=resolved_status,
        payment_method=payment_method or "Transfer",
        notes=notes,
        outstanding_before=outstanding_before,
        outstanding_after=outstanding_after,
        transfer_group_id=transfer_group_id,
        settled_at=settled_at,
    )

    return {
        "id": settlement_id,
        "amount": amount_value,
        "outstanding_before": outstanding_before,
        "outstanding_after": outstanding_after,
        "status": resolved_status,
    }


def backfill_settlements_from_transfers_with_cursor(cursor) -> int:
    ensure_settlements_schema_with_cursor(cursor)

    rows = cursor.execute(
        """
        SELECT
            out_tx.transfer_group_id,
            out_tx.beneficiary_vault_id,
            out_tx.vault_id,
            in_tx.vault_id,
            out_tx.amount,
            out_tx.date,
            COALESCE(out_tx.notes, '')
        FROM transactions out_tx
        JOIN transactions in_tx
            ON in_tx.transfer_group_id = out_tx.transfer_group_id
            AND in_tx.transaction_type = ?
            AND in_tx.is_deleted = 0
        WHERE out_tx.transaction_type = ?
        AND out_tx.is_deleted = 0
        AND out_tx.transfer_group_id IS NOT NULL
        AND COALESCE(out_tx.notes, '') LIKE 'Shared settlement:%'
        AND NOT EXISTS (
            SELECT 1
            FROM settlements s
            WHERE s.transfer_group_id = out_tx.transfer_group_id
        )
        ORDER BY out_tx.date ASC, out_tx.id ASC
        """,
        (
            TRANSFER_IN,
            TRANSFER_OUT,
        ),
    ).fetchall()

    created = 0
    for row in rows:
        transfer_group_id = row[0]
        shared_vault_id = int(row[1])
        from_participant_id = int(row[2])
        to_participant_id = int(row[3])
        amount = as_money(row[4])
        settlement_date = str(row[5])
        notes = row[6] or None

        insert_settlement_with_cursor(
            cursor,
            shared_vault_id=shared_vault_id,
            from_participant_id=from_participant_id,
            to_participant_id=to_participant_id,
            amount=amount,
            status=SETTLEMENT_STATUS_FULL,
            payment_method="Transfer",
            notes=notes,
            outstanding_before=amount,
            outstanding_after=0,
            transfer_group_id=transfer_group_id,
            settled_at=f"{settlement_date}T12:00:00+00:00" if len(settlement_date) == 10 else settlement_date,
        )
        created += 1

    return created


def _row_to_settlement(row, current_vault_id: int) -> dict:
    from_id = int(row[2])
    to_id = int(row[3])
    from_name = row[12] or "Unknown"
    to_name = row[13] or "Unknown"
    direction = "sent" if from_id == current_vault_id else "received"

    return {
        "id": int(row[0]),
        "vaultId": int(row[1]),
        "fromParticipantId": from_id,
        "toParticipantId": to_id,
        "fromName": from_name,
        "toName": to_name,
        "fromInitials": participant_initials(from_name),
        "toInitials": participant_initials(to_name),
        "amount": as_money(row[4]),
        "status": row[5],
        "paymentMethod": row[6],
        "notes": row[7],
        "outstandingBefore": None if row[8] is None else as_money(row[8]),
        "outstandingAfter": None if row[9] is None else as_money(row[9]),
        "settledAt": str(row[10]) if row[10] is not None else None,
        "createdAt": str(row[11]) if row[11] is not None else None,
        "direction": direction,
        "isReceived": direction == "received",
    }


def get_settlement_history(
    shared_vault_id: int,
    current_vault_id: int,
    *,
    direction: str = SETTLEMENT_FILTER_ALL,
    limit: int = 20,
    offset: int = 0,
) -> dict:
    ensure_settlements_schema()
    conn = get_connection()
    try:
        cursor = conn.cursor()
        backfill_settlements_from_transfers_with_cursor(cursor)
        conn.commit()

        params: list = [shared_vault_id]
        direction_clause = ""
        normalized = (direction or SETTLEMENT_FILTER_ALL).lower()

        if normalized == SETTLEMENT_FILTER_RECEIVED:
            direction_clause = "AND s.to_participant_id = ?"
            params.append(current_vault_id)
        elif normalized == SETTLEMENT_FILTER_SENT:
            direction_clause = "AND s.from_participant_id = ?"
            params.append(current_vault_id)

        count_row = cursor.execute(
            f"""
            SELECT COUNT(*)
            FROM settlements s
            WHERE s.shared_vault_id = ?
            {direction_clause}
            """,
            tuple(params),
        ).fetchone()
        total = int(count_row[0]) if count_row else 0

        page_params = list(params)
        page_params.extend([limit + 1, offset])

        rows = cursor.execute(
            f"""
            SELECT
                s.id,
                s.shared_vault_id,
                s.from_participant_id,
                s.to_participant_id,
                s.amount,
                s.status,
                s.payment_method,
                s.notes,
                s.outstanding_before,
                s.outstanding_after,
                s.settled_at,
                s.created_at,
                from_vault.name,
                to_vault.name
            FROM settlements s
            LEFT JOIN vaults from_vault
                ON from_vault.id = s.from_participant_id
            LEFT JOIN vaults to_vault
                ON to_vault.id = s.to_participant_id
            WHERE s.shared_vault_id = ?
            {direction_clause}
            ORDER BY s.settled_at DESC, s.id DESC
            LIMIT ? OFFSET ?
            """,
            tuple(page_params),
        ).fetchall()

        has_more = len(rows) > limit
        page_rows = rows[:limit]
        items = [_row_to_settlement(row, current_vault_id) for row in page_rows]

        return {
            "items": items,
            "hasMore": has_more,
            "nextOffset": offset + len(items) if has_more else None,
            "total": total,
            "limit": limit,
            "offset": offset,
        }
    finally:
        conn.close()
